version: '3.4'

services:
  planningboard:
    image: planningboard
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8090:80"
    depends_on:
      - migrations
      - db
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "1Secure*Password1"
      ACCEPT_EULA: "Y"
    ports:
    - "14331:1433"
    depends_on:
      - migrations
  migrations:
    build:
      context: .
      dockerfile: Migrations.Dockerfile